namespace: fleet-app-example
targetCustomizations:
- name: development
  clusterSelector:
    matchExpressions:
    - key: cluster-role
      operator: NotIn
      values:
        - management
  yaml:
    overlays:
    # Refers to overlays/noreplication folder
    - noreplication

- name: development
  clusterSelector:
    matchLabels:
      cluster-role: management
  yaml:
    overlays:
    # Refers to overlays/scale3 folder
    - scale3
